### ISSUE TITLE
Warning: Failed prop type: The prop `isRequired` is marked as required in `COMPONENT_NAME`, but its value is `undefined`.

### ISSUE THREAD

**Issue by Licen-it** [ztoben/immutable-prop-types#6]
**Describe the bug**
Using `ImmutablePropTypes.listOf()` is triggering the following error:
```
Warning: Failed prop type: The prop `isRequired` is marked as required in `COMPONENT_NAME`, but its value is `undefined`.
```

**To Reproduce**
1. create a component and let it have an immutable list as property defined by a particular share (shape is not important, i tried different shapes and all triggers the error)
2. run that component and react will trigger the warning in the description

**Expected behavior**
No warning should appear in the console

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 68.0.3440.106 (Official Build) (64-bit)

**Comment by ztoben** [comment]
Yeah, this repo is a WIP and needs a full rewrite. I wouldn't be using it in any production type environments for now.
